/*
 * This file is part of Safester.                                    
 * Copyright (C) 2019, KawanSoft SAS
 * (https://www.Safester.net). All rights reserved.                                
 *                                                                               
 * Safester is free software; you can redistribute it and/or                 
 * modify it under the terms of the GNU Lesser General Public                    
 * License as published by the Free Software Foundation; either                  
 * version 2.1 of the License, or (at your option) any later version.            
 *                                                                               
 * Safester is distributed in the hope that it will be useful,               
 * but WITHOUT ANY WARRANTY; without even the implied warranty of                
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU             
 * Lesser General Public License for more details.                               
 *                                                                               
 * You should have received a copy of the GNU Lesser General Public              
 * License along with this library; if not, write to the Free Software           
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  
 * 02110-1301  USA
 * 
 * Any modifications to this file must keep this entire header
 * intact.
 */
package com.safelogic.pgp.api.toolkit;

/**
 * <br>
 * Main Interface that defines all the cGeep API methods for
 * OpenPGP encryption.
 * &copy; 2009 -  <a href="http://www.safelogic.com">SafeLogic</a>
 * <br>
 * 
 * @author Nicolas de Pomereu 
 */

public interface ICgeepApi
{        
    public static final String SIGN_KEY_NOT_FOUND  = "SIGN_KEY_NOT_FOUND";
    public static final String SIGN_NOT_SIGNED     = "SIGN_NOT_SIGNED";
    public static final String SIGN_BAD            = "SIGN_BAD";
    public static final String SIGN_OK             = "SIGN_OK";
    
    //////////////////////////////////////////////////////////////////////////
    // Error management functions                                           //
    //////////////////////////////////////////////////////////////////////////
    
    /**
     * Test if the last operation is OK. If an error has been raised,will return false. 
     *  
     * @return true if the last operation is Ok.
     */
    public boolean isOperationOk();

    /**
     * Return the error code generated by the last operation. Will be null if no error has been raised.
     * 
     * @return the Error Code as a generic string
     */
    public String getErrorCode();

    /**
     * Return the Java Exception generated by the last operation. Will be null if no error has been raised.
     * 
     * @return the Java Exception as a String
     */
    public String getException();
    
    /**
     * Return the Java Stack Trace of the last operation. Will be null if no error has been raised.
     * 
     * @return the last Java Exception stack trace as a String. 
     */
    public String getStackTrace();
    
    
    /**
     * Test if the last operation is OK for a task. 
     * If an error has been raised,will return false. 
     * @param taskNumber    a task number to reference the operation (default to 0)
     *       
     * @return true if the last operation is Ok.
     */
    public boolean isOperationOkForTask(int taskNumber);

    /**
     * Return the error code generated by the last operation for a task.
     * Will be null if no error has been raised.
     * @param taskNumber    a task number to reference the operation (default to 0)
     * 
     * @return the Error Code as a generic string
     */
    public String getErrorCodeForTask(int taskNumber);

    /**
     * Return the Java Exception generated by the last operation for a task.
     * Will be null if no error has been raised.
     * @param taskNumber    a task number to reference the operation (default to 0)
     * 
     * @return the Java Exception as a String
     */
    public String getExceptionForTask(int taskNumber);
    
    /**
     * Return the Java Stack Trace of the last operation. 
     * Will be null if no error has been raised.
     * @param taskNumber    a task number to reference the operation (default to 0)
     * @return the last Java Exception stack trace as a String. 
     */
    public String getStackTraceForTask(int taskNumber);    
    
    //////////////////////////////////////////////////////////////////////////
    // Version                                         //
    //////////////////////////////////////////////////////////////////////////
    
    /**
     * Display the current cGeep OpenPGP API Version
     */
    public String getVersion();
        
    //////////////////////////////////////////////////////////////////////////
    // Command Line                                                         //
    //////////////////////////////////////////////////////////////////////////
            
    /**
     * Add a parameter to the OpenPGP command line to execute
     * @param parameter  the String parameter to add to the command before execution
     */    
    void addCommandLineParameter(String parameter);

    /**
     * Execute the OpenPGP command (for c++ dll) with the parameters passed by addParameter
     */    
    void executeCommandLine();    
    
    //////////////////////////////////////////////////////////////////////////
    // Key management functions                                             //
    //////////////////////////////////////////////////////////////////////////
    
    /**
     * Get the directory that contains the OpenPGP keyring to use
     * @return the directory that contains the OpenPGP keyring to use
     */
    public String getKeyRingDirectory();
        
    /**
     * Defines the directory that contains the OpenPGP keyring to use
     * <br>
     * Default value is "user.home" if this function is never called.
     * 
     * @param directory         the directory that will contain the OpenPGP keyring
     * <br>Examples:
     * <br>- Windows: c:\myPgpDirectory
     * <br>- Unix/Linux:   /home/myPgpDirectory                                   
     */
    public void setKeyRingDirectory(String directory);
        
      
    /**
     * 
     * Generate a new OpenPGP key pair
     * <br>
     * N.B: the key will be stored in the keyring set by setKeyRingDirectory().
     * <br>
     * <br> 
     * @param userId            the OpenPGP User ID of the key to generate. 
     *                          Usually an email + a name (higly recommanded).
     *                          (Example : "John Smith &lt;john@smith.com&gt;")
     * @param passphrase        the passphrase to use to protect (encrypt) the OpenPGP private key
     * @param algoAsym          the Asymmetric algorithm to use 
     * @param keyLengthAsym     the key length of the symmetric key
     * @param algoSym           the Symmetric algorithm to use
     * @param expirationDate    the expiration date in "YY/MM/DD" format or "NEVER"
     * 
     */
    public void generateKeyPair(String userId, 
                                char[] passphrase, 
                                String algoAsym, 
                                int keyLengthAsym, 
                                String algoSym, 
                                String expirationDate
                                );
    
    /**
     * Generate a revocation Certificate for the specified OpenPGP key
     * 
     * @param userId            the OpenPGP User ID of the key to modify the passphrase
     * @param passphraseOld     the present passphrase of the OpenPGP private key
     * @param passphraseNew     the new passphrase to attribute to the OpenPGP key
     */
    
    public void changePassphrase(String userId, char [] passphraseOld, char [] passphraseNew);
    
    
    /**
     * List all matching OpenPGP keys into a formated String:
     * <tt>
     <br> pub   1024D/08941581 2008-12-15 
     <br> uid                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Smith Daniel &lt;Daniel@smith.com&gt;
     <br> sub   2048g/B139C386 2008-12-15
     <br>   
     <br> pub   1024s/4D4FC24F 2006-05-09
     <br> uid                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Nicolas de Pomereu &lt;ndepomereu@safelogic.com&gt;
     <br> uid                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [jpeg image of size 3907]
     <br> sub   1024r/8C1EA9FA 2006-05-09
     * </tt>
     * 
     * @param substring    the substring of OpenPGP UserIDs to display. If null, all will be displayed
     * @return  all matching keys
     */
    public String listKeys(String substring);
    
    
    /**
     * Export a OpenPGP public key in armor format.
     * 
     * @param userId        the OpenPGP User ID
     * @param file          the file into which to export the OpenPGP public key
     */
    public void exportPublicKey(String userId, String file);
    
    
    /**
     * Export a OpenPGP key pair (public key & private key) in armor format.
     * 
     * @param userId        the OpenPGP User ID
     * @param file          the file into which to export the OpenPGP key pair
     */
    public void exportPublicAndPrivateKey(String userId, String file);    
    
    
    /**
     * Import a OpenPGP key contained in a file into the OpenPGP keyring in use.
     * <br>
     * N.B: the key will be stored in the OpenPGP keyring set by setKeyRingDirectory().
     * <br>
     * <br>
     * The function may import depending on the file content either:
     * <br> - 1) A OpenPGP public key only.
     * <br> - 2) Both a OpenPGP public key and it's associated OpenPGP private key.
     * 
     * @param file          the file that contains the OpenPGP key
     */
    public void importKey(String file); 
    
    
    /**
     * Sign a OpenPGP public key using it's OpenPGP User ID
     *  
     * @param userId            the OpenPGP user ID of the public key to sign
     * @param userIdPrivate     the OpenPGP User ID of the private key used to sign
     * @param passphrase        the passphrase of the OpenPGP private key used to sign
     */
    public void signKey(String userId, String userIdPrivate, char [] passphrase);
    
    /**
     * Remove a signature from a OpenPGP public key
     *  
     * @param userId            the OpenPGP User ID of the public key to remove the signature from
     * @param userIdPrivate     the OpenPGP User ID of the private key used to sign
     * @param passphrase        the passphrase of the OpenPGP private key used to sign
     */
    public void removeKeySignature( String userId, 
                                    String userIdPrivate, 
                                    char [] passphrase);   
        
    /**
     * Add a photo to a OpenPGP private key
     * <br>
     * N.B: it's possible to add only one photo to a OpenPGP key.
     * 
     * @param userId            the OpenPGP User ID of the private key to add a photo to 
     * @param photo		        the file that contains the photo
     * @param passphrase        the passphrase of the private OpenPGP key used to sign
     */
    public void addPhoto(String userId, String photo, char [] passphrase);  
    
    
    /**
     * Delete a photo from a OpenPGP private key
     * 
     * @param userId    the OpenPGP User ID of the OpenPGP private key to delete a photo from 
     */
    public void deletePhoto(String userId);  
    
    
    /**
     * Delete a OpenPGP public key (and if it exists, the private OpenPGP key associated)
     * 
     * @param userId    the user ID of the OpenPGP key to delete
     */
    public void deleteKey(String userId);
    
    
    /**
     * Generate a revocation Certificate for the specified OpenPGP key
     * 
     * @param userId            the OpenPGP User ID of the key to revoke
     * @param passphrase        the passphrase of the private OpenPGP key to revoke
     */
    public void revokeKey(String userId, char [] passphrase);
    
    
    /**
     * Search for a list of OpenPGP keys on a HKP Server
     * 
     * @param hkpServerUrl      the full URL (with port) of the HKP Server to search
     * @param substring         the substring of OpenPGP User ID to search for
     * 
     * @return  a list of OpenPGP keys in the "mr" (Machine Readable format)
     */
    public String searchKeysOnHkpServer(String hkpServerUrl, String substring);
    
    /**
     * Retrieve a OpenPGP key from a HKP server
     * 
     * @param hkpServerUrl      the full URL (with port) of the HKP Server to search
     * @param keyId             the exact OpenPGP Key ID of the key to retrieve
     * 
     * @return     the OpenPGP public key in armor format
     */
    public String receiveKey(String hkpServerUrl, String keyId);
        
    /**
     * Send a OpenPGP key on a HKP server
     * 
     * @param hkpServerUrl  URL of the HKP server
     * @param userId        User id of the OpenPGP key to publish
     */
    
    public void sendKey(String hkpServerUrl, String userId);
        
    
    //////////////////////////////////////////////////////////////////////////
    // Wipe functions                                                       //
    //////////////////////////////////////////////////////////////////////////
    
    /**
     * Wipe a file (Secure delete) 
     * @param file          the file to wipe (full path)
     * @param rounds        the number of rounds (1 to 7)
     * @param taskNumber    a task number to reference the operation (default to 0)
     */
    public void wipe(String file, int rounds, int taskNumber);

    
    //////////////////////////////////////////////////////////////////////////
    // Symmetric Encryption/Decryption management functions                 //
    //////////////////////////////////////////////////////////////////////////
    
    /**
     * Sets the charset to use for encoding.
     * <br>
     * If not specified, encryption use the character encoding of the underlying platform
     */
    public void setCharset(String charset);
        
    /**
     * Extract the current Charset in use
     */
    
    public String getCharset();

    
    /**
     * Return the preferred algorithm in use for OpenPGP symmetric encryption.
     * <br>
     * Defaults to AES-256.
     * @return the preferred algorithm in use for OpenPGP symmetric encryption.
     */
    public String getSymmetricAlgorithm();    
    
    
    /**
     * Set the preferred algorithm for OpenPGP symmetric encryption.
     * 
     * @param algorithm         the algorithm to use for OpenPGP symmetric encryption
     * 
     */
    public void setSymmetricAlgorithm(String algorithm);
    
    
    /**
     * Encrypt symmetrically a String with a passphrase
     * 
     * @param string        the string to encrypt
     * @param passphrase    the passphrase to use for OpenPGP symmetric encryption
     * 
     * @return the encrypted string
     */
    public String encryptSymmetricString(String string, char [] passphrase);
        
    /**
     * Decrypt symmetrically a String with a passphrase
     * 
     * @param string        the string to decrypt
     * @param passphrase    the passphrase to use for OpenPGP symmetric decryption
     * 
     * @return the encrypted string
     */
    public String decryptSymmetricString(String string, char [] passphrase);    
    
    
    /**
     * Define if the signed and/or encrypted files will be PGP armored
     * 
     * @param armorMode if true, signed and/or encrypted files will be PGP armored
     */
    public void setArmorModeForFiles(boolean armorMode);
    
    
    //////////////////////////////////////////////////////////////////////////
    // Symmetric Encryption/Decryption for file functions                   //
    //////////////////////////////////////////////////////////////////////////    
        
    /**
     * Encrypt symmetrically a file with a passphrase
     * 
     * @param file          the file to encrypt (full path)
     * @param encryptedFile the resulting encrypted file (full path) 
     * @param passphrase    the passphrase to use for symmetric encryption
     * @param taskNumber    a task number to reference the operation (default to 0)
     * 
     */
    public void encryptSymmetric(String file, String encryptedFile, 
                                 char [] passphrase, int taskNumber);
    
    
    /**
     * Decrypt symmetrically a file with a passphrase.
     * 
     * @param file          the file to decrypt (full path)
     * @param decryptedFile the resulting decrypted file (full path)
     * @param passphrase    the passphrase to use for symmetric decryption
     * @param taskNumber    a task number to reference the operation (default to 0)
     * 
     */
    public void decryptSymmetric(String file, String decryptedFile, char [] passphrase, int taskNumber);    
    

    /**
     * Return percentage (%) that have been processed so far by the file encryption/decryption
     * operation referenced by a task number.
     * <br><br>
     * This method is to be used if a file encryption/decryption 
     * is called inside a separated thread.
     * <br>
     * It can be used to set a progress indicator, for example.
     * 
     * @param taskNumber        the task number that reference the file 
     * @return                  the percentage processed for the encryption/decryption operation
     */
    public int getPercentProcessedForTask(int taskNumber);

    /**
     * Cancel a background task.
     * @param taskNumber        the task number thats references the operation.
     */
    public boolean cancelTask(int taskNumber);
        
    
    //////////////////////////////////////////////////////////////////////////
    // Asymmetric Encryption/Decryption string functions                    //
    //////////////////////////////////////////////////////////////////////////
        
    /**
     * Reset the list of OpenPGP public keys for the next asymmetric encryption operation
     */
    public void resetRecipientsKeys();
        
    /**
     * Add a OpenPGP ublic key in the list of recipients for the next asymmetric encryption
     * operation 
     * @param userId    the OpenPGP User ID  of the public key to add
     */
    public void addRecipientKey(String userId);
    
    /**
     * Encrypt a string for a list of OpenPGP recipients created by calls to addRecipientKey()
     * 
     * @param string        the string to encrypt
     * 
     * @return the encrypted string in armor format            
     */
    public String encryptString(String string);
    
    
    /**
     * Return from the keyring the OpenPGP User ID of the key that may decrypt the encryptedString
     * @param encryptedString        the encrypted string in armor format    
     * 
     * @return  the (first) matching OpenPGP User ID found in the keyring. 
     *          <br>null if no matching OpenPGP User ID is found
     * 
     */
    public String getUserIdForStringDecryption(String encryptedString);
    
    
    /**
     * Decrypt a string that has been asymmetrically for a OpenPGP User ID 
     * 
     * @param encryptedString   the encrypted string in armor format    
     * @param userId            the OpenPGP User ID  of the private key to use for decryption
     * @param passphrase        the passphrase of the OpenPGP private key to use
     * 
     * @return the decrypted string           
     */
    public String decryptString(String encryptedString, String userId, char [] passphrase);
        
    
    //////////////////////////////////////////////////////////////////////////
    // Asymmetric Encryption/Decryption file functions                      //
    //////////////////////////////////////////////////////////////////////////    
    
    /**
     * Encrypt asymmetrically a file with for a list of OpenPGP User ID/srecipients 
     * created by calls to addRecipientKey()
     * 
     * @param file          the file to encrypt (full path)
     * @param encryptedFile the resulting encrypted file (full path) 
     * @param taskNumber    a task number to reference the operation (default to 0)
     * 
     */
    public void encrypt(String file, String encryptedFile, int taskNumber);
    
    
    /**
     * Return from the keyring the OpenPGP User ID of the key that may decrypt 
     * the encryptedFile
     * @param encryptedFile        the encrypted file
     * 
     * @return  the (first) matching User ID found in the keyring. 
     *          <br>null if no matching User ID is found
     * 
     */
    public String getUserIdForDecryption(String encryptedFile);    
    
    /**
     * Decrypt a file that has been asymmetrically for a OpenPGP User ID 
     * 
     * @param file              the file to decrypt (full path)
     * @param decryptedFile     the resulting decrypted file (full path)
     * @param userId            the OpenPGP User ID  of the private key to use for decryption
     * @param passphrase        the passphrase of the OpenPGP private key to use
     * @param taskNumber        a task number to reference the operation (default to 0)
     * 
     * if the file is also signed,
     * the signature status is verified with the getSignatureStatusForTask() function  
     */
    public void decrypt(String file, String decryptedFile, String userId, char [] passphrase, int taskNumber);    
            
    //////////////////////////////////////////////////////////////////////////
    // File signature & verification functions                                             //
    //////////////////////////////////////////////////////////////////////////      
        
    /**
     * returns the OpenPGP signature status for the last decrypt/verify operation on files
     * 
     * @return  the status of the verify operation:
     * <br> - SIGN_NOT_SIGNED: the decrypted file is not signed
     * <br> - SIGN_OK: the signature is ok and valid
     * <br> - SIGN_FAIL: the signature is invalid 
     * <br> - SIGN_KEY_NOT_FOUND: the signing key is not found in the keyring   
     */
    public String getSignatureStatus();
    
    /**
     * returns the signature status for the specified task decrypt/verify operation on files
     * @param taskNumber                a task number to reference the operation (default to 0)
     * 
     * @return  the status of the verify operation:
     * <br> - SIGN_NOT_SIGNED: the decrypted file is not signed
     * <br> - SIGN_OK: the signature is ok and valid
     * <br> - SIGN_FAIL: the signature is invalid 
     * <br> - SIGN_KEY_NOT_FOUND: the signing key is not found in the keyring   
     */
    public String getSignatureStatusForTask(int taskNumber);    
    
    /**
     * Sign a file with a detached signature.
     * 
     * @param file                      the file to sign (full path)
     * @param detachedFileSignature     the detached signature to create (full path)
     * @param userId                    the OpenPGP User ID  of the private key to use for signature               
     * @param passphrase                the passphrase of the OpenPGP private key to use
     * @param taskNumber                a task number to reference the operation (default to 0)
     */
    public void signDetached(String file, String detachedFileSignature, String userId, char[] passphrase, int taskNumber);  
    
    /**
     * Verify the OpenPGP signature of a file with a detached signature.
     *     
     * @param file                      the file to check the signature
     * @param detachedFileSignature     the detached signature file for signature check
     * @param taskNumber                a task number to reference the operation (default to 0)
     *     
     * The signature status is verified with the getSignatureStatusForTask() function    
     */
    public void verifyDetached(String file, String detachedFileSignature, int taskNumber);
    
    
    //////////////////////////////////////////////////////////////////////////
    // File signature + encryption function                                 //
    //////////////////////////////////////////////////////////////////////////       
    
    /**
     * Sign and Encrypt asymmetrically a file with for a list of OpenPGP User ID/recipients 
     * created by calls to addRecipientKey()
     * 
     * @param file              the file to encrypt (full path)
     * @param encryptedFile     the resulting signed and encrypted file (full path) 
     * @param userId            the OpenPGP User ID  of the private key to use for signature
     * @param passphrase        the passphrase of the OpenPGP private key to use
     * @param taskNumber        a task number to reference the signature & encryption operation (default to 0)  
     */
    public void signAndEncrypt(String file, String encryptedFile, String userId, char [] passphrase, int taskNumber);
            
}

