/*
 * This file is part of Safester.                                    
 * Copyright (C) 2019, KawanSoft SAS
 * (https://www.Safester.net). All rights reserved.                                
 *                                                                               
 * Safester is free software; you can redistribute it and/or                 
 * modify it under the terms of the GNU Lesser General Public                    
 * License as published by the Free Software Foundation; either                  
 * version 2.1 of the License, or (at your option) any later version.            
 *                                                                               
 * Safester is distributed in the hope that it will be useful,               
 * but WITHOUT ANY WARRANTY; without even the implied warranty of                
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU             
 * Lesser General Public License for more details.                               
 *                                                                               
 * You should have received a copy of the GNU Lesser General Public              
 * License along with this library; if not, write to the Free Software           
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  
 * 02110-1301  USA
 * 
 * Any modifications to this file must keep this entire header
 * intact.
 */
package net.safester.clientserver.test;

import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;
import net.safester.application.SafesterLookAndFeelManager;

/**
 *
 * @author Nicolas de Pomereu
 */
public class SearchJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public SearchJFrame1() {
        initComponents();
        
        this.setTitle("Search Messages");
        
        //Init date interval to last month
        Calendar now = Calendar.getInstance();
        jXDatePickerEnd.setDate(now.getTime());
        now.add(Calendar.MONTH, -1);
        jXDatePickerStart.setDate(now.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        From = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        From1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        Folder = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabelSearchDate = new javax.swing.JLabel();
        jXDatePickerStart = new org.jdesktop.swingx.JXDatePicker();
        jLabelAnd = new javax.swing.JLabel();
        jXDatePickerEnd = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setPreferredSize(new java.awt.Dimension(433, 10));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Find");
        jLabel1.setMaximumSize(new java.awt.Dimension(49, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(49, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(49, 16));
        jPanel1.add(jLabel1);

        jTextField1.setToolTipText("");
        jTextField1.setMinimumSize(new java.awt.Dimension(200, 22));
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel1.add(jTextField1);

        jButton1.setText("SEARCH");
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        From.setText("To");
        From.setMaximumSize(new java.awt.Dimension(49, 16));
        From.setMinimumSize(new java.awt.Dimension(49, 16));
        From.setPreferredSize(new java.awt.Dimension(49, 16));
        jPanel2.add(From);

        jTextField2.setText("                         ");
        jTextField2.setToolTipText("");
        jTextField2.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel2.add(jTextField2);

        getContentPane().add(jPanel2);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        From1.setText("From");
        From1.setMaximumSize(new java.awt.Dimension(49, 16));
        From1.setMinimumSize(new java.awt.Dimension(49, 16));
        From1.setPreferredSize(new java.awt.Dimension(49, 16));
        jPanel4.add(From1);

        jTextField3.setText("                         ");
        jTextField3.setToolTipText("");
        jTextField3.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField3.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel4.add(jTextField3);

        getContentPane().add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Folder.setText("Folder");
        Folder.setMaximumSize(new java.awt.Dimension(49, 16));
        Folder.setMinimumSize(new java.awt.Dimension(49, 16));
        Folder.setPreferredSize(new java.awt.Dimension(49, 16));
        jPanel5.add(Folder);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inbox", "Sent" }));
        jPanel5.add(jComboBox1);

        getContentPane().add(jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);

        jPanel6.setPreferredSize(new java.awt.Dimension(315, 74));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelSearchDate.setText("Between");
        jPanel6.add(jLabelSearchDate);
        jPanel6.add(jXDatePickerStart);

        jLabelAnd.setText("and");
        jPanel6.add(jLabelAnd);
        jPanel6.add(jXDatePickerEnd);

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            /*
            try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
            }
            }
            } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            
            */
            
            SafesterLookAndFeelManager.setLookAndFeel();
        } catch (IOException ex) {
            Logger.getLogger(SearchJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SearchJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(SearchJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(SearchJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(SearchJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Folder;
    private javax.swing.JLabel From;
    private javax.swing.JLabel From1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAnd;
    private javax.swing.JLabel jLabelSearchDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerEnd;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerStart;
    // End of variables declaration//GEN-END:variables
}
